In [ ]:
# Write a code to square a given number
given_number = list(range(1,10))
print(given_number)

squared_number = []

for numbers in given_number:
  squared_number.append(numbers**2)

print(squared_number)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
given_number = list(range(10))
given_number

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list_of_numbers = [1, 2, 4, 6, 11, 14, 17, 20]

even_squared_number = []
for every_number in list_of_numbers:
  if every_number % 2 == 0:
   even_squared_number.append(every_number**2)
print(even_squared_number)

[4, 16, 36, 196, 400]


In [ ]:
squared_number =[numbers**2 for numbers in given_number ]
print(squared_number)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
even_squared_number =[every_number**2 for every_number in list_of_numbers if every_number % 2 == 0]
print(even_squared_number)

[4, 16, 36, 196, 400]


In [ ]:
odd_numbered_square = [numbers**2 if numbers % 2 !=0 else numbers**3 for numbers in list_of_numbers]
print(odd_numbered_square)

[1, 8, 64, 216, 121, 2744, 289, 8000]


In [ ]:
user_input = input()

if user_input[::1] == user_input[::-1]:
  print('Given word is palindrome')
else:
  print('Given word is not palindrome')

5555
Given word is palindrome


In [ ]:
print(given_number)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
given_number[4] = 8
print(given_number)

[0, 1, 2, 3, 8, 5, 6, 7, 8, 9]


In [ ]:
alphabet_position = list(range(0,27))
print(alphabet_position)
alphabet =' ,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z'
alphabet_list = alphabet.split(',')
print(alphabet_list)
dictionary = dict(zip(alphabet_position,alphabet_list))
print(dictionary)
list_of_keys = list(dictionary.keys())
print(list_of_keys)
list_of_values = list(dictionary.values())
print(list_of_values)
index_h = list_of_values.index('h')
print(index_h)
list_of_keys.index(index_h)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
{0: ' ', 1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z'}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
8


8

In [ ]:
import numpy as np

prime_array = np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


In [ ]:
type(prime_array)

numpy.ndarray

In [ ]:
l =[2,3,5,7,11]
type(l)

list

In [ ]:
another_array = np.array([[2,3],[5,7]])
print(another_array)

[[2 3]
 [5 7]]


In [ ]:
type(another_array)

numpy.ndarray

In [ ]:
three_D_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_D_array)
print(three_D_array.shape)
print(three_D_array.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
fourD_array = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(fourD_array)
print(fourD_array.shape)
print(fourD_array.ndim)
print(fourD_array.size)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(2, 2, 2, 2)
4
16


In [ ]:
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print(array_of_integers)
print(array_of_integers.shape)
print(array_of_integers.ndim)
print(array_of_integers.ndim)
print(array_of_integers.dtype)


[0 1 2 3 4 5 6 7 8 9]
(10,)
1
1
int64


In [ ]:
class car():
  def __init__(self,modelname,yearm,price):
    self.modelname = modelname
    self.yearm = yearm
    self.price = price
  def price_inc(self):
     self.price = self.price*1.15

     return self.price







honda = car('City',2020,1000000)
tata = car('Nexon',2019,1200000)

honda.cc = 1500
tata.cc = 1900
'''honda.modelname = 'City'
honda.yearm = 2020
honda.price = 1000000

tata.modelname = 'Nexon'
tata.yearm = 2019
tata.price = 1200000'''

print(honda.__dict__)
print(tata.__dict__)
print(honda.price)

(honda.price_inc())

{'modelname': 'City', 'yearm': 2020, 'price': 1000000, 'cc': 1500}
{'modelname': 'Nexon', 'yearm': 2019, 'price': 1200000, 'cc': 1900}
1000000


1150000.0

In [ ]:
#def area_rectangle(length, breadth):
  #area_of_rectangle =(length*breadth)
  #return area_of_rectangle





In [ ]:
#sample_retangle = area_rectangle(2.5,3)
#sample_retangle

In [ ]:
class rectangle():
  def __init__(self,length,breadth):
    self.length = length
    self.breadth = breadth

  def area_of_rectangle(self):
    return self.length*self.breadth

  def perimetre_of_rectangle(self):
    return 2*self.length + 2 * self.breadth

In [ ]:
sample_retangle = rectangle(2,3)

sample_retangle.area_of_rectangle()


6

In [ ]:
j=10
k=10

In [ ]:
print(j,k)

10 10


In [ ]:
print(id(j),id(k))

133785205064208 133785205064208


In [ ]:
a = 'hello'
c = ' 20'
b = 'jitesh'
print(a+c+b)

hello 20jitesh


##Arithmetic operator

In [ ]:
a = 10
b = 20
print(a*b,a/b,b%3,a**b,a//3)
print(a/b)
print(a%b)
print(a**b)
print(a//b)

200 0.5 2 100000000000000000000 3
0.5
10
100000000000000000000
0


## Assignment operator

In [ ]:
x = 5
x += 3
x

8

In [ ]:
x-=2
x

6

## Comparisons operator

In [ ]:
x = 10
y= 20
print(x==y)
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)

False
True
False
True
False
True


###Logical Operators

In [ ]:
x = 10
y = 20

print(x==10 and x<y)
print(x==10 or x>y)
print(not(x==5 and x>y))


True
True
True


In [ ]:
k = int(input("Write a number:"))
print(k**2)

Write a number:555
308025


In [ ]:
k = int(input("Write a number: "))
print(k**2)


Write a number: 3232
10445824


In [ ]:
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    elif n == 0 or n == 1:
        return 1
    else:
        result = 1
        for i in range(2, n + 1):
            result *= i
        return result

num = int(input("Enter a number: "))
print(f"The factorial of {num} is {factorial(num)}")


Enter a number: 7
The factorial of 7 is 5040


In [ ]:
string1 = "Hello"
print('H' in string1)

True


In [ ]:
print(range(1,10))

range(1, 10)


In [ ]:
for i in range(1,10):
  print(i*i)

1
4
9
16
25
36
49
64
81
