In [ ]:
# Write a code to square a given number
given_number = list(range(1,10))
print(given_number)

squared_number = []

for numbers in given_number:
  squared_number.append(numbers**2)

print(squared_number)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
given_number = list(range(10))
given_number

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list_of_numbers = [1, 2, 4, 6, 11, 14, 17, 20]

even_squared_number = []
for every_number in list_of_numbers:
  if every_number % 2 == 0:
   even_squared_number.append(every_number**2)
print(even_squared_number)

[4, 16, 36, 196, 400]


In [ ]:
squared_number =[numbers**2 for numbers in given_number ]
print(squared_number)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
even_squared_number =[every_number**2 for every_number in list_of_numbers if every_number % 2 == 0]
print(even_squared_number)

[4, 16, 36, 196, 400]


In [ ]:
odd_numbered_square = [numbers**2 if numbers % 2 !=0 else numbers**3 for numbers in list_of_numbers]
print(odd_numbered_square)

[1, 8, 64, 216, 121, 2744, 289, 8000]


In [ ]:
user_input = input()

if user_input[::1] == user_input[::-1]:
  print('Given word is palindrome')
else:
  print('Given word is not palindrome')

5555
Given word is palindrome


In [ ]:
print(given_number)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
given_number[4] = 8
print(given_number)

[0, 1, 2, 3, 8, 5, 6, 7, 8, 9]


In [ ]:
alphabet_position = list(range(0,27))
print(alphabet_position)
alphabet =' ,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z'
alphabet_list = alphabet.split(',')
print(alphabet_list)
dictionary = dict(zip(alphabet_position,alphabet_list))
print(dictionary)
list_of_keys = list(dictionary.keys())
print(list_of_keys)
list_of_values = list(dictionary.values())
print(list_of_values)
index_h = list_of_values.index('h')
print(index_h)
list_of_keys.index(index_h)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
{0: ' ', 1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z'}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
8


8

In [ ]:
import numpy as np

prime_array = np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


In [ ]:
type(prime_array)

numpy.ndarray

In [ ]:
l =[2,3,5,7,11]
type(l)

list

In [ ]:
another_array = np.array([[2,3],[5,7]])
print(another_array)

[[2 3]
 [5 7]]


In [ ]:
type(another_array)

numpy.ndarray

In [ ]:
three_D_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_D_array)
print(three_D_array.shape)
print(three_D_array.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
fourD_array = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(fourD_array)
print(fourD_array.shape)
print(fourD_array.ndim)
print(fourD_array.size)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(2, 2, 2, 2)
4
16


In [ ]:
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print(array_of_integers)
print(array_of_integers.shape)
print(array_of_integers.ndim)
print(array_of_integers.ndim)
print(array_of_integers.dtype)


[0 1 2 3 4 5 6 7 8 9]
(10,)
1
1
int64


In [ ]:
class car():
  def __init__(self,modelname,yearm,price):
    self.modelname = modelname
    self.yearm = yearm
    self.price = price
  def price_inc(self):
     self.price = self.price*1.15

     return self.price







honda = car('City',2020,1000000)
tata = car('Nexon',2019,1200000)

honda.cc = 1500
tata.cc = 1900
'''honda.modelname = 'City'
honda.yearm = 2020
honda.price = 1000000

tata.modelname = 'Nexon'
tata.yearm = 2019
tata.price = 1200000'''

print(honda.__dict__)
print(tata.__dict__)
print(honda.price)

(honda.price_inc())

{'modelname': 'City', 'yearm': 2020, 'price': 1000000, 'cc': 1500}
{'modelname': 'Nexon', 'yearm': 2019, 'price': 1200000, 'cc': 1900}
1000000


1150000.0

In [ ]:
#def area_rectangle(length, breadth):
  #area_of_rectangle =(length*breadth)
  #return area_of_rectangle





In [ ]:
#sample_retangle = area_rectangle(2.5,3)
#sample_retangle

In [ ]:
class rectangle():
  def __init__(self,length,breadth):
    self.length = length
    self.breadth = breadth

  def area_of_rectangle(self):
    return self.length*self.breadth

  def perimetre_of_rectangle(self):
    return 2*self.length + 2 * self.breadth

In [ ]:
sample_retangle = rectangle(2,3)

sample_retangle.area_of_rectangle()


6

In [ ]:
j=10
k=10

In [ ]:
print(j,k)

10 10


In [ ]:
print(id(j),id(k))

133785205064208 133785205064208


In [ ]:
a = 'hello'
c = ' 20'
b = 'jitesh'
print(a+c+b)

hello 20jitesh


##Arithmetic operator

In [ ]:
a = 10
b = 20
print(a*b,a/b,b%3,a**b,a//3)
print(a/b)
print(a%b)
print(a**b)
print(a//b)

200 0.5 2 100000000000000000000 3
0.5
10
100000000000000000000
0


## Assignment operator

In [ ]:
x = 5
x += 3
x

8

In [ ]:
x-=2
x

6

## Comparisons operator

In [ ]:
x = 10
y= 20
print(x==y)
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)

False
True
False
True
False
True


###Logical Operators

In [ ]:
x = 10
y = 20

print(x==10 and x<y)
print(x==10 or x>y)
print(not(x==5 and x>y))


True
True
True


In [ ]:
k = int(input("Write a number:"))
print(k**2)

Write a number:555
308025


In [ ]:
k = int(input("Write a number: "))
print(k**2)


Write a number: 3232
10445824


In [ ]:
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    elif n == 0 or n == 1:
        return 1
    else:
        result = 1
        for i in range(2, n + 1):
            result *= i
        return result

num = int(input("Enter a number: "))
print(f"The factorial of {num} is {factorial(num)}")


Enter a number: 7
The factorial of 7 is 5040


In [ ]:
string1 = "Hello"
print('H' in string1)

True


In [ ]:
print(range(1,10))

range(1, 10)


In [ ]:
for i in range(1,10):
  print(i*i)

1
4
9
16
25
36
49
64
81


In [ ]:
class rectangle():
  def __init__(self,length,breadth):
    self.length = length
    self.breadth = breadth

  def area_of_rectangle(self):
    return self.length*self.breadth

  def perimetre_of_rectangle(self):
    return 2*self.length + 2 * self.breadth



In [ ]:
class Product:
    def __init__(self, price):
        self.__price = price  # Private attribute

    def get_price(self):
        return self.__price

    def set_price(self, price):
        if price > 0:
            self.__price = price
        else:
            print("Invalid price")

In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name            # Public attribute
        self._age = age             # Protected attribute

    def display_info(self):
        print(f"Name: {self.name}, Age: {self._age}")

    def _display_age(self):
        print(f"Age: {self._age}")
person = Person("Alice", 30)
person.display_info()  # Output: Name: Alice, Age: 30

# Accessing public attribute
print(person.name)  # Output: Alice

# Accessing protected attribute (not recommended)
print(person._age)  # Output: 30

# Accessing protected method (not recommended)
person._display_age()  # Output: Age: 30


Name: Alice, Age: 30
Alice
30
Age: 30


In Python, classes and instances can have attributes that store data. These attributes can be classified into two types: class variables and instance variables. Understanding the difference between these two is crucial for managing data correctly in object-oriented programming.

**Class Variables**

**Definition:**

**Class variables** are attributes that are shared by all instances of a class. They are defined within the class but outside any instance methods.


**Scope:**
They belong to the class itself and are shared among all instances of the class.


**Usage:**
Class variables are used when you want to have a common value that should be the same for all instances of the class.



**Instance Variables**

Definition:

Instance variables are attributes that are specific to each instance of a class. They are usually defined within the __init__ method or other instance methods.

**Scope:**

They belong to the instance of the class and are not shared among instances.
Usage:
Instance variables are used to maintain data that is unique to each instance of the class.


In [ ]:
class Dog:
    # Class variable
    species = "Canis familiaris"

    def __init__(self, name, age):
        # Instance variables
        self.name = name
        self.age = age

# Creating instances of the Dog class
dog1 = Dog("Buddy", 5)
dog2 = Dog("Lucy", 3)

# Accessing class variables
print(dog1.species)  # Output: Canis familiaris
print(dog2.species)  # Output: Canis familiaris

# Accessing instance variables
print(dog1.name)  # Output: Buddy
print(dog1.age)   # Output: 5
print(dog2.name)  # Output: Lucy
print(dog2.age)   # Output: 3

# Modifying class variable
Dog.species = "Canis lupus familiaris"
print(dog1.species)  # Output: Canis lupus familiaris
print(dog2.species)  # Output: Canis lupus familiaris

# Modifying instance variable
dog1.age = 6
print(dog1.age)  # Output: 6
print(dog2.age)  # Output: 3

In [ ]:
class Dog:
  species= "German shephered"
  def __init__(self, name, age):   #instance variable: they are defined using __init__
    self.name = name
    self.age = age

dog1 = Dog("Kitto",4)
dog2 = Dog("Chotu",3)

print(dog1.species)
print(dog2.name,dog2.age)



German shephered
Chotu 3


In [ ]:
class Person:
  def __init__(self,name, age):
    self.name = name
    self._age = age

  def display_info(self):
    print(self.name, self._age)

person = Person("Virat", 34)
person.display_info()




Virat 34


In [ ]:
def findHCF(x,y):
    if x > y:
        smaller = y
    else:
        smaller = x
    for i in range(1, smaller+1):
        if ((x % i == 0) and (y % i == 0)):
            HCF = i
    return HCF


inp1 = int(input("Enter 1st number to find HCF\n"))
inp2 = int(input("Enter 2nd number to find HCF \n:"))

print("HCF Of given two numbers is", findHCF(inp1,inp2))



Enter 1st number to find HCF
7
Enter 2nd number to find HCF 
:9
HCF Of given two numbers is 1


In [ ]:
print(10*'jitesh')

jiteshjiteshjiteshjiteshjiteshjiteshjiteshjiteshjiteshjitesh


In [ ]:
x = input("Write a word to reversr it:\n")

for i in  range(-1,-len(x)-1,-1):
    print(x[i], end = "")



Write a word to reversr it:
Jitesh
hsetiJ

In [ ]:
s = range(5)
for i in s:
    print(i)

0
1
2
3
4


In [ ]:
#Syntax of string slicing s[start:end:step]
s = "Python Programming"
for i in range(len(s)):
    print(i," : " ,s[i])

s = "Python Programming"
j = len(s)

for i in range(j):
    print(i,s[i],-j)
    j -= 1


0  :  P
1  :  y
2  :  t
3  :  h
4  :  o
5  :  n
6  :   
7  :  P
8  :  r
9  :  o
10  :  g
11  :  r
12  :  a
13  :  m
14  :  m
15  :  i
16  :  n
17  :  g
0 P -18
1 y -17
2 t -16
3 h -15
4 o -14
5 n -13
6   -12
7 P -11
8 r -10
9 o -9
10 g -8
11 r -7
12 a -6
13 m -5
14 m -4
15 i -3
16 n -2
17 g -1


In [ ]:
x = 5
y = 10

x,y = y,x

print(x)
print(y)

10
5


In [ ]:
class Bank:
    def __init__(self, pin, initial_balance=0):
        self._pin = pin
        self.balance = initial_balance

    def _verify_pin(self, pin):
        return self._pin == pin

    def withdraw(self, amount, pin):
        if self._verify_pin(pin):
            if amount > self.balance:
                print("Insufficient funds.")
            else:
                self.balance -= amount
                print(f"Withdrawal successful. You withdrew {amount}. Your new balance is {self.balance}.")
        else:
            print("Invalid PIN. Transaction failed.")

    def deposit(self, amount, pin):
        if self._verify_pin(pin):
            self.balance += amount
            print(f"Deposit successful. You deposited {amount}. Your new balance is {self.balance}.")
        else:
            print("Invalid PIN. Transaction failed.")

# Example usage:
# Create a Bank object with an initial balance of 1000 and PIN 1234
my_bank = Bank(pin=1234, initial_balance=1000)

# Try to withdraw 200 with the correct PIN
my_bank.withdraw(amount=200, pin=1234)

# Try to deposit 300 with the correct PIN
my_bank.deposit(amount=300, pin=1234)

# Try to withdraw 200 with an incorrect PIN
my_bank.withdraw(amount=200, pin=1111)

# Try to deposit 300 with an incorrect PIN
my_bank.deposit(amount=300, pin=1111)


Withdrawal successful. You withdrew 200. Your new balance is 800.
Deposit successful. You deposited 300. Your new balance is 1100.
Invalid PIN. Transaction failed.
Invalid PIN. Transaction failed.


In [ ]:
class Bank:

    def __init__(self, pin = 2580 , amount = 2000):
        self.__pin = pin
        self._amount = amount

    def verify_pin(self, pin):
        return self.__pin == pin

    def check_balance(self , pin):
        if self.verify_pin(pin):
            return "Available balance is", self._amount
        else:
            return "Invalid pin, Try again"


    def withdrawl(self, pin, withdrawl):
        if self.verify_pin(pin):
            if withdrawl > self._amount:
                return "Insufficient Fund"
            else:
                self._amount -= withdrawl
                print(f"withdrawl amount is {withdrawl}, Available balance is  {self._amount}")
        else:
            return "Invalid Pin, Try again with corrected pin"
    def deposit(self, pin, deposit):
        if self.verify_pin(pin):
            self._amount += deposit
            print(f"Deposited amount is {deposit}, Available balance is {self._amount}")
        else:
            return "Invalid pin. Try again with valid pin"


my_bank = Bank()
#amount = float(input("Enter the amount you want to withdraw \n"))
enter_pin = int(input("Enter your secret pin to proceed the transaction \n"))
print(my_bank.check_balance(enter_pin))

#my_bank.withdrawl(enter_pin,amount)
print("\n")
#amount = float(input("Enter the amount you want to deposit \n"))
#enter_pin = int(input("Enter your secret pin to proceed the transaction \n"))
#my_bank.deposit(enter_pin,amount)







Enter your secret pin to proceed the transaction 
2580
('Available balance is', 2000)




In [ ]:
class Srudents:
    school = "Hindu College"


    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3


    def get_average(self):
        return (self.m1+self.m2+self.m3)/3
    @classmethod
    def info(cls):
        return cls.school

    @staticmethod
    def get_info():
        print("This is Hindu college batch")

s1 = Srudents(23,56,67)
print(s1.get_average())
s2 = Srudents( 34,89,65)
print(s2.get_average())
print(s1.info())

print(s1.get_info())

48.666666666666664
62.666666666666664
Hindu College
This is Hindu college batch
None


In [ ]:
class A:


    def feature1(self):
        print("Feature 1 is working")

    def feature2(self):
        print("Feature 2 is working")


class B(A):

    def feature3(self):
        print("feature3 is working")

    def feature4(self):
        print("feature4 is working")

class C(B):

    def feature6(self):
        print(" Feature 6 is working")

    def feature5(self):
        print(" Feature 5 is working")

a1 = A()

b1 = B()

c1 = C()

a1.feature1()
a1.feature2()
b1.feature1()
b1.feature2()
b1.feature3()
c1.feature4()
c1.feature1()
c1.feature2()
c1.feature3()
c1.feature4()
c1.feature5()
c1.feature6()






Feature 1 is working
Feature 2 is working
Feature 1 is working
Feature 2 is working
feature3 is working
feature4 is working
Feature 1 is working
Feature 2 is working
feature3 is working
feature4 is working
 Feature 5 is working
 Feature 6 is working


In [ ]:
# Multi level inheritance

class A:

    def feature1(self):
        print("Feature 1 is working")


class B:

    def feature2(self):
        print("Feature 2 is working")


class C(A,B):

    def feature3(self):
        print("feature 3 is working")


a1 = A()
a1.feature1()

b1 = B()

b1.feature2()

c1 = C()

c1.feature1()
c1.feature2()
c1.feature3()

Feature 1 is working
Feature 2 is working
Feature 1 is working
Feature 2 is working
feature 3 is working


In [ ]:
# Multilevel inheritance

class A:
    def __init__(self):
        print("In _init_ of A")

    def feature1(self):
        print("feature 1 is working")


class B(A):

    def __init__(self):
        super().__init__()
        print("In _init_ of B")

    def feature2(self):
        print("feature 2 is working")


class C(B,A):

    def __init__(self):
        super().__init__()
        print("In _init_ of C")

    def feature3(self):
        print("feature 3 is working")


a = A()
a.feature1()

b =B()
b.feature1()
b.feature2()


c =C()
c.feature2()
c.feature1()
c.feature3()

In _init_ of A
feature 1 is working
In _init_ of A
In _init_ of B
feature 1 is working
feature 2 is working
In _init_ of A
In _init_ of B
In _init_ of C
feature 2 is working
feature 1 is working
feature 3 is working


In [ ]:
class A:
    def __init__(self):
        print("In init of A")


    def feature1(self):
        print("feature 1-A is working")

class B:

    def __init__(self):
        print("in init of B ")

    def feature1(self):
        print("Feature 1-B is working")


class C(A,B):

    def __init__(self):
        super().__init__()
        print("In init of C")

    def feature3(self):
        print("Feature 3 is working")


a = C()
a.feature1()
a.feature1()
a.feature3()


In init of A
In init of C
feature 1-A is working
feature 1-A is working
Feature 3 is working
